llm: gpt-4
review:
  language: ko
  rules:
    - "코드가 명확하고 유지보수가 쉬운가?"
    - "불필요한 클래스, 메서드, 주석이 포함되어 있는가?"
    - "예외 처리는 적절히 되어 있는가?"
    - "REST API 규약을 잘 지키고 있는가?"
    - "Service와 Repository 레이어가 명확히 분리되어 있는가?"
    - "보안상 취약한 코드(SQL 인젝션, 인증 누락 등)는 없는가?"
    - "커밋 메시지가 Conventional Commits 규칙을 따르고 있는가? (build, ci, docs, feat, fix, perf, refactor, test 타입 사용)"
  filters:
    include:
      - "**/*.java"
    exclude:
      - "**/test/**"
      - "**/build/**"
      - "**/out/**"
