spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${GOOGLE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  data:
    redis:
      host: ${REDIS_USER}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always

  config:
      import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_KEY}
            scope:
              - email
              - profile

logging:
  level:
    root: WARN
    odyssey: INFO

jwt:
  secret: ${SECRET_KEY}
