spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_KEY}
            scope:
              - email
              - profile

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
    org.springframework.security: DEBUG

jwt:
  secret: ${SECRET_KEY}

upload:
  thumbnail-dir: src/main/resources/static/uploads/thumbnails/
  thumbnail-url-prefix: /uploads/thumbnails/
