spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}           # ?: jdbc:postgresql://localhost:5432/your_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

jwt :
  secret : {SECRET_KEY}

  logging:
    level:
      org:
        springframework: security = DEBUG

upload:
  thumbnail-dir: src/main/resources/static/uploads/thumbnails/
  thumbnail-url-prefix: /uploads/thumbnails/
