name: Deploy to Development

on:
  pull_request:
    types: [closed]
    branches: [develop]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Deploy to Dev Server
        run: |
          echo "🚀 Deploying to DEV server..."
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Environment,Values=dev" \
            --parameters 'commands=[
              "cd /home/ubuntu",
              "git pull origin develop",
              "chmod +x gradlew",
              "./gradlew clean bootJar",
              "pkill -f java || true",
              "nohup java -jar build/libs/*.jar > app.log 2>&1 &"
            ]'
